### ISSUE TITLE
A few more Apple products

### ISSUE THREAD

**Issue by brandonweiss** [thoughtbot/foundry-core#10]
I notice there's a MacBook Pro, iMac, Apple Thunderbolt Display, iPad, and iPhone. It'd be great to complete the set with an iPod touch, MacBook Air, Mac mini, Mac Pro, and Apple TV. :heart:

**Comment by brandonweiss** [comment]
Bueller?

**Comment by whmii** [comment]
@brandonweiss sorry for the radio silence. I will be adding an apple tv. I want to see how the mac pro turns out but it might be so nondescript that it looks like nothing. I'd like to add a couple more notebook computers as well.

**Comment by brandonweiss** [comment]
Yay!

The Mac Pro? Did you mean the MacBook Pro? I don't imagine the Mac Pro will get a another redesign any time soon...

**Comment by whmii** [comment]
oh, I meat how an illiustration of it turns out. it might just look like a black rectangle. ha! I'll give it a shot

**Comment by brandonweiss** [comment]
Ah, got it!

**Comment by whmii** [comment]
@brandonweiss https://github.com/thoughtbot/foundry-core/pull/17
